---
- hosts: ubuntu
  become: yes
  gather_facts: yes

  pre_tasks:
  - name: update cache
    tags: always
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_distribution == "Ubuntu"
    
  roles:
    - system
    - httpd
    - maria_db
    - perl
    - php
    - ocs
