- include_vars: centos.yml
  when: ansible_distribution == "Centos"

- include: centos.yml
  when: ansible_distribution == "Centos"

- include_vars: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

