- block:
  
  - name: Ensure dnf-plugins are installed CentOS8
    yum:
      name: dnf-plugins-core
      state: present
   
  - name: Enable dnf modure for CentOS8
    shell: |
      dnf config-manager --set-enabled powertools
      dnf module enable -y php:remi-{{ php_enablerepo }}
    args:
      warn: false
    register: dnf_module_enable
    changed_when: "'Nothing to do' not in dnf_module_enable.stdout "

  - name: Ensure php and php packeges are installed
    dnf:
      name: '{{ packages_centos }}'
      state: present

  - name: Enable php-fpm is running
    service:
      name: php-fpm
      state: restarted
      enabled: yes

  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version | int >= 8 

- block:

  - name: Install packages php Ubuntu
    apt:
      name: "{{ packages_ubuntu }}"
      state: present

  - name: Ensure php service is running
    service:
      name: "php{{ php_version_ubuntu }}-fpm"
      state: restarted

  when:
  - ansible_distribution == "Ubuntu"